CREATE DATABASE IF NOT EXISTS laravel_db;
CREATE DATABASE IF NOT EXISTS go_db;

DROP USER IF EXISTS 'laravel'@'%';
DROP USER IF EXISTS 'go'@'%';

CREATE USER 'laravel'@'%' IDENTIFIED BY 'laravel';
CREATE USER 'go'@'%' IDENTIFIED BY 'go';

GRANT ALL PRIVILEGES ON laravel_db.* TO 'laravel'@'%';
GRANT ALL PRIVILEGES ON go_db.* TO 'go'@'%';

FLUSH PRIVILEGES;
